apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data-svc
  namespace: elkstack
  labels:
    component: elasticsearch
    role: data
spec:
  selector:
    component: elasticsearch
    role: data
  ports:
  - name: http
    port: 9200
